walkerCivilians=[
["RyanZombieC_man_1walker"],
["RyanZombieC_man_polo_1_Fwalker"],
["RyanZombieC_man_polo_2_Fwalker"],
["RyanZombieC_man_polo_4_Fwalker"],
["RyanZombieC_man_polo_5_Fwalker"],
["RyanZombieC_man_polo_6_Fwalker"],
["RyanZombieC_man_p_fugitive_Fwalker"],
["RyanZombieC_man_w_worker_Fwalker"],
["RyanZombieC_scientist_Fwalker"],
["RyanZombieC_man_hunter_1_Fwalker"],
["RyanZombieC_man_pilot_Fwalker"],
["RyanZombieC_journalist_Fwalker"],
["RyanZombieC_Oresteswalker"]
];

walkerSoldiers=[
["RyanZombieB_Soldier_02_fwalker"],
["RyanZombieB_Soldier_02_f_1walker"],
["RyanZombieB_Soldier_02_f_1_1walker"],
["RyanZombieB_Soldier_03_fwalker"],
["RyanZombieB_Soldier_03_f_1walker"],
["RyanZombieB_Soldier_03_f_1_1walker"],
["RyanZombieB_Soldier_04_fwalker"],
["RyanZombieB_Soldier_04_f_1walker"],
["RyanZombieB_Soldier_04_f_1_1walker"],
["RyanZombieB_Soldier_05_fwalker"],
["RyanZombieB_Soldier_lite_Fwalker"],
["RyanZombieB_Soldier_lite_F_1walker"],
["RyanZombieB_RangeMaster_Fwalker"]
];



slowCivilians=[
["RyanZombieC_man_1slow"],
["RyanZombieC_man_polo_1_Fslow"],
["RyanZombieC_man_polo_2_Fslow"],
["RyanZombieC_man_polo_4_Fslow"],
["RyanZombieC_man_polo_5_Fslow"],
["RyanZombieC_man_polo_6_Fslow"],
["RyanZombieC_man_p_fugitive_Fslow"],
["RyanZombieC_man_w_worker_Fslow"],
["RyanZombieC_scientist_Fslow"],
["RyanZombieC_man_hunter_1_Fslow"],
["RyanZombieC_man_pilot_Fslow"],
["RyanZombieC_journalist_Fslow"],
["RyanZombieC_Orestesslow"]
];

slowSoldiers=[
["RyanZombieB_Soldier_02_fslow"],
["RyanZombieB_Soldier_02_f_1slow"],
["RyanZombieB_Soldier_02_f_1_1slow"],
["RyanZombieB_Soldier_03_fslow"],
["RyanZombieB_Soldier_03_f_1slow"],
["RyanZombieB_Soldier_03_f_1_1slow"],
["RyanZombieB_Soldier_04_fslow"],
["RyanZombieB_Soldier_04_f_1slow"],
["RyanZombieB_Soldier_04_f_1_1slow"],
["RyanZombieB_Soldier_05_fslow"],
["RyanZombieB_Soldier_lite_Fslow"],
["RyanZombieB_Soldier_lite_F_1slow"]
];

mediumCivilians=[
["RyanZombieC_man_1medium"],
["RyanZombieC_man_polo_1_Fmedium"],
["RyanZombieC_man_polo_2_Fmedium"],
["RyanZombieC_man_polo_4_Fmedium"],
["RyanZombieC_man_polo_5_Fmedium"],
["RyanZombieC_man_polo_6_Fmedium"],
["RyanZombieC_man_p_fugitive_Fmedium"],
["RyanZombieC_man_w_worker_Fmedium"],
["RyanZombieC_scientist_Fmedium"],
["RyanZombieC_man_hunter_1_Fmedium"],
["RyanZombieC_man_pilot_Fmedium"],
["RyanZombieC_journalist_Fmedium"],
["RyanZombieC_Orestesmedium"],
["RyanZombieB_RangeMaster_Fmedium"]
];

mediumSoldiers=[
["RyanZombieB_Soldier_02_fmedium"],
["RyanZombieB_Soldier_02_f_1medium"],
["RyanZombieB_Soldier_02_f_1_1medium"],
["RyanZombieB_Soldier_03_fmedium"],
["RyanZombieB_Soldier_03_f_1medium"],
["RyanZombieB_Soldier_03_f_1_1medium"],
["RyanZombieB_Soldier_04_fmedium"],
["RyanZombieB_Soldier_04_f_1medium"],
["RyanZombieB_Soldier_04_f_1_1medium"],
["RyanZombieB_Soldier_05_fmedium"],
["RyanZombieB_Soldier_lite_Fmedium"],
["RyanZombieB_Soldier_lite_F_1medium"]
];

fastCivilians=[
["RyanZombieC_man_1"],
["RyanZombieC_man_polo_1_F"],
["RyanZombieC_man_polo_2_F"],
["RyanZombieC_man_polo_4_F"],
["RyanZombieC_man_polo_5_F"],
["RyanZombieC_man_polo_6_F"],
["RyanZombieC_man_p_fugitive_F"],
["RyanZombieC_man_w_worker_F"],
["RyanZombieC_scientist_F"],
["RyanZombieC_man_hunter_1_F"],
["RyanZombieC_man_pilot_F"],
["RyanZombieC_journalist_F"],
["RyanZombieC_Orestes"],
["RyanZombieB_RangeMaster_F"]
];

fastSoldiers=[
["RyanZombieB_Soldier_02_f"],
["RyanZombieB_Soldier_02_f_1"],
["RyanZombieB_Soldier_02_f_1_1"],
["RyanZombieB_Soldier_03_f"],
["RyanZombieB_Soldier_03_f_1"],
["RyanZombieB_Soldier_03_f_1_1"],
["RyanZombieB_Soldier_04_f"],
["RyanZombieB_Soldier_04_f_1"],
["RyanZombieB_Soldier_04_f_1_1"],
["RyanZombieB_Soldier_05_f"],
["RyanZombieB_Soldier_lite_F"],
["RyanZombieB_Soldier_lite_F_1"],
["RyanZombieB_RangeMaster_Fslow"]
];

boss=[
["RyanZombieboss1"],
["RyanZombieboss2"],
["RyanZombieboss3"],
["RyanZombieboss4"],
["RyanZombieboss5"],
["RyanZombieboss6"],
["RyanZombieboss7"],
["RyanZombieboss8"],
["RyanZombieboss9"],
["RyanZombieboss10"],
["RyanZombieboss11"],
["RyanZombieboss12"],
["RyanZombieboss13"],
["RyanZombieboss14"]
];

spiders=[
["RyanZombieSpider1"],
["RyanZombieSpider2"],
["RyanZombieSpider3"],
["RyanZombieSpider4"],
["RyanZombieSpider5"],
["RyanZombieSpider6"],
["RyanZombieSpider7"],
["RyanZombieSpider8"],
["RyanZombieSpider9"],
["RyanZombieSpider10"],
["RyanZombieSpider11"],
["RyanZombieSpider12"],
["RyanZombieSpider13"],
["RyanZombieSpider14"]
];

crawlers=[
["RyanZombieCrawler1"],
["RyanZombieCrawler2"],
["RyanZombieCrawler3"],
["RyanZombieCrawler4"],
["RyanZombieCrawler5"],
["RyanZombieCrawler6"],
["RyanZombieCrawler7"],
["RyanZombieCrawler8"],
["RyanZombieCrawler9"],
["RyanZombieCrawler10"],
["RyanZombieCrawler11"],
["RyanZombieCrawler12"],
["RyanZombieCrawler13"],
["RyanZombieCrawler14"]
];