// ExileZ 2.0 by Patrix87 of http:\\multi-jeux.quebec //

Private [
"_lootqte",
"_maxOfEach",
"_triggerPosition",
"_items",
"_item",
"_cargoBox",
"_lootBox"
];

_lootqte = 45;
_maxOfEach = 3;
_triggerPosition = _this select 0;

_items =[
"B_Carryall_cbr",
"B_Carryall_khk",
"B_Carryall_mcamo",
"B_Carryall_ocamo",
"B_Carryall_oli",
"B_Carryall_oucamo",
"B_Parachute",
"V_RebreatherB",
"V_RebreatherIA",
"V_RebreatherIR",
"V_PlateCarrier1_blk",
"V_PlateCarrier1_rgr",
"V_PlateCarrierL_CTRG",
"V_PlateCarrier2_rgr",
"V_PlateCarrier3_rgr",
"V_PlateCarrierH_CTRG",
"V_PlateCarrierIAGL_dgtl",
"V_PlateCarrierIAGL_oli",
"V_PlateCarrierGL_blk",
"V_PlateCarrierGL_mtp",
"V_PlateCarrierGL_rgr",
"H_HelmetO_ocamo",
"H_HelmetO_oucamo",
"U_B_FullGhillie_ard",
"U_B_FullGhillie_lsh",
"U_B_FullGhillie_sard",
"U_I_FullGhillie_ard",
"U_I_FullGhillie_lsh",
"U_I_FullGhillie_sard",
"U_O_FullGhillie_ard",
"U_O_FullGhillie_lsh",
"U_O_FullGhillie_sard",
"U_B_Wetsuit",
"U_I_Wetsuit",
"U_O_Wetsuit",
"arifle_MX_SW_Black_F",
"arifle_MX_SW_F",
"rhs_weap_m249_pip_L",
"rhs_weap_m249_pip_L_para",
"rhs_weap_m249_pip_S",
"rhs_weap_m249_pip_S_para",
"rhs_weap_m249_pip_L_vfg",
"rhs_weap_m249_pip_S_vfg",
"LMG_Mk200_F",
"rhs_weap_pkm",
"rhs_weap_pkp",
"rhs_weap_m240B",
"rhs_weap_m240G",
"rhs_weap_m240B_CAP",
"LMG_Zafir_F",
"MMG_01_hex_F",
"MMG_01_tan_F",
"MMG_02_black_F",
"MMG_02_camo_F",
"MMG_02_sand_F",
"rhs_weap_ak74m",
"rhs_weap_ak74m_camo",
"rhs_weap_ak74m_camo_folded",
"rhs_weap_ak74m_desert",
"rhs_weap_ak74m_desert_folded",
"rhs_weap_ak74m_folded",
"rhs_weap_ak74m_camo_npz",
"rhs_weap_ak74m_desert_npz",
"rhs_weap_ak74m_npz",
"rhs_weap_ak74m_gp25",
"rhs_weap_ak74m_gp25_folded",
"rhs_weap_ak74m_gp25_npz",
"arifle_Katiba_C_F",
"arifle_Katiba_F",
"arifle_Katiba_GL_F",
"rhs_weap_m4",
"rhs_weap_m4_carryhandle",
"rhs_weap_m4_carryhandle_pmag",
"rhs_weap_m4_grip",
"rhs_weap_m4_grip2",
"rhs_weap_m4_m203",
"rhs_weap_m4_m320",
"arifle_Mk20_F",
"arifle_Mk20_plain_F",
"arifle_Mk20_GL_F",
"arifle_Mk20_GL_plain_F",
"arifle_Mk20C_F",
"arifle_Mk20C_plain_F",
"arifle_TRG20_F",
"arifle_TRG21_F",
"arifle_TRG21_GL_F",
"rhs_weap_ak103",
"rhs_weap_ak103_npz",
"rhs_weap_ak103_gp25",
"rhs_weap_ak103_gp25_npz",
"rhs_weap_ak104",
"rhs_weap_ak104_npz",
"rhs_weap_ak105",
"rhs_weap_ak105_npz",
"rhs_weap_akm",
"rhs_weap_akm_gp25",
"rhs_weap_akms",
"rhs_weap_akms_gp25",
"rhs_weap_m16a4",
"rhs_weap_m16a4_carryhandle",
"rhs_weap_m16a4_carryhandle_pmag",
"rhs_weap_m16a4_carryhandle_grip",
"rhs_weap_m16a4_carryhandle_grip_pmag",
"rhs_weap_m16a4_grip",
"rhs_weap_m16a4_carryhandle_M203",
"rhs_weap_m27iar",
"rhs_weap_m4a1",
"rhs_weap_m4a1_carryhandle",
"rhs_weap_m4a1_carryhandle_pmag",
"rhs_weap_m4a1_carryhandle_grip",
"rhs_weap_m4a1_carryhandle_grip2",
"rhs_weap_m4a1_grip",
"rhs_weap_m4a1_grip2",
"rhs_weap_m4a1_carryhandle_m203",
"rhs_weap_m4a1_m203",
"rhs_weap_m4a1_m320",
"rhs_weap_m4a1_blockII",
"rhs_weap_m4a1_blockII_KAC",
"rhs_weap_m4a1_blockII_grip2",
"rhs_weap_m4a1_blockII_grip2_KAC",
"rhs_weap_m4a1_blockII_M203",
"rhs_weap_M590_5RD",
"rhs_weap_M590_8RD",
"rhs_weap_mk18",
"rhs_weap_mk18_KAC",
"rhs_weap_mk18_grip2",
"rhs_weap_mk18_grip2_KAC",
"rhs_weap_mk18_m320",
"arifle_MX_Black_F",
"arifle_MX_F",
"arifle_MX_GL_Black_F",
"arifle_MX_GL_F",
"arifle_MXC_Black_F",
"arifle_MXC_F",
"rhs_weap_asval",
"rhs_weap_asval_npz",
"arifle_SDAR_F",
"rhs_weap_svdp",
"rhs_weap_svdp_wd",
"rhs_weap_svds",
"rhs_weap_svdp_npz",
"rhs_weap_svdp_wd_npz",
"rhs_weap_svds_npz",
"arifle_MXM_Black_F",
"arifle_MXM_F",
"srifle_DMR_01_F",
"rhs_weap_m14ebrri",
"rhs_weap_m39",
"rhs_weap_sr25",
"rhs_weap_sr25_ec",
"srifle_EBR_F",
"srifle_DMR_03_F",
"srifle_DMR_03_khaki_F",
"srifle_DMR_03_multicam_F",
"srifle_DMR_03_tan_F",
"srifle_DMR_03_woodland_F",
"srifle_DMR_06_camo_F",
"srifle_DMR_06_olive_F",
"srifle_DMR_02_camo_F",
"srifle_DMR_02_F",
"srifle_DMR_02_sniper_F",
"srifle_DMR_05_blk_F",
"srifle_DMR_05_hex_F",
"srifle_DMR_05_tan_f",
"srifle_DMR_04_F",
"srifle_DMR_04_Tan_F",
"rhs_weap_XM2010",
"rhs_weap_XM2010_d",
"rhs_weap_XM2010_sa",
"rhs_weap_XM2010_wd",
"srifle_LRR_camo_F",
"srifle_LRR_F",
"srifle_GM6_camo_F",
"srifle_GM6_F",
"optic_Arco",
"optic_Hamr",
"optic_MRCO",
"rhs_acc_1p29",
"rhs_acc_pso1m2",
"rhsusf_acc_ACOG",
"rhsusf_acc_ACOG2",
"rhsusf_acc_ACOG3",
"optic_DMS",
"rhsusf_acc_LEUPOLDMK4",
"optic_AMS",
"optic_AMS_khk",
"optic_AMS_snd",
"optic_KHS_blk",
"optic_KHS_hex",
"optic_KHS_old",
"optic_KHS_tan",
"optic_SOS",
"rhsusf_acc_LEUPOLDMK4_2",
"optic_LRPS",
"rhs_acc_1pn93_1",
"rhs_acc_1pn93_2",
"optic_NVS",
"DemoCharge_Remote_Mag",
"SLAMDirectionalMine_Wire_Mag",
"IEDLandSmall_Remote_Mag",
"IEDUrbanSmall_Remote_Mag",
"HandGrenade",
"HandGrenade",
"HandGrenade",
"Exile_Item_SafeKit",
"Exile_Item_CodeLock",
"Exile_Item_CodeLock",
"Exile_Item_CodeLock",
"NVGoggles",
"NVGoggles_INDEP",
"NVGoggles_OPFOR",
"Rangefinder",
"Laserdesignator",
"Laserdesignator_02",
"Laserdesignator_03"
];

//big ass boxes
_cargoBox = [

	"Land_Cargo40_blue_F",
	"Land_Cargo40_brick_red_F",
	"Land_Cargo40_cyan_F",
	"Land_Cargo40_grey_F",
	"Land_Cargo40_light_blue_F",
	"Land_Cargo40_light_green_F",
	"Land_Cargo40_military_green_F",
	"Land_Cargo40_orange_F",
	"Land_Cargo40_red_F",
	"Land_Cargo40_sand_F",
	"Land_Cargo40_white_F",
	"Land_Cargo40_yellow_F"
	
] call BIS_fnc_selectRandom;
	
	
/* DON'T EDIT BELOW ADVANCED USERS ONLY */
//////////////////////////////////////////


_lootBox = _cargoBox createvehicle _triggerPosition;

clearMagazineCargoGlobal _lootBox;
clearWeaponCargoGlobal _lootBox;
clearItemCargoGlobal _lootBox;
_lootBox enableRopeAttach false;
_lootBox setVariable ["permaLoot",true];
_lootBox allowDamage false;

for "_i" from 1 to _lootqte do {
	_item = _items call BIS_fnc_selectRandom;
	_lootBox addItemCargoGlobal [_item, (ceil random _maxOfEach)];
};
